config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :herbs, only: [ :index, :show, :update, :create, :destroy ]
      resources :herb_types, only: [ :index, :show, :update, :create, :destroy ]
      resources :misc_ingredients, only: [ :index, :show, :update, :create, :destroy ]
    end
  end

  root to: 'pages#home'
  get '/api', to: 'pages#api'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto text-right">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link mr-2" %>
      </li>
      <li class="nav-item">
        <%= link_to "API", api_path, class: "nav-link mr-3" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Profile", "#", class: "nav-link mr-2" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.svg", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Preferences", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link mr-2" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>